### ISSUE TITLE
Repository Cleanup

### ISSUE THREAD

**Issue by bbengfort** [rotationalio/rotational.io#2]
@rebeccabilbro would it be ok if I did the following things to clean up and consolidate the web repos?

- [x] Delete the old github.com/rotationalio/rotational.io repository (after merging #1) 
- [x] Rename this repository to rotational.io (in case we don't use GitHub pages for hosting forever) 
- [x] Change "master" to "main"

I wanted to check with you since you set up the repository and didn't want to disrupt any thoughts you had about structure.

**Comment by rebeccabilbro** [comment]
Sure!

**Comment by bbengfort** [comment]
I haven't changed `master` to `main` yet since I have open changes, but I have changed the name of the repo.

To get the new setup, you'll have to either delete and reclone the repository or run the following steps:

```
$ git remote set-url origin git@github.com:rotationalio/rotational.io.git
```
